version: "3"

services:

  web:
    build:
      context: api
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - redis
    volumes:
      - './api:/api'
    ports:
     - "5001:5001"

  worker:
    build:
      context: celery-queue
      dockerfile: Dockerfile
    depends_on:
      - redis

  monitor:
    build:
      context: celery-queue
      dockerfile: Dockerfile
    entrypoint: flower
    command:  -A tasks --port=5555 --broker=redis://redis:6379/0
    depends_on:
      - redis
    ports:
     - "5555:5555"

  redis:
    image: 'redis:4-alpine'
    ports:
      - '6379'

  postgres:
    image: 'postgres:9.6-alpine'
    environment:
      POSTGRES_DB: 'test_db'
      PGDATA: '/var/lib/postgresql/data/pgdata'
      POSTGRES_USER: test_db
      POSTGRES_PASSWORD: test_db
    volumes:
      - 'test-postgres:/var/lib/postgresql/data/pgdata'
    ports:
      - '5432'

volumes:
  test-postgres:
